package modelo;
// Generated 02-dic-2018 21:50:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {
     private String ccodalu;
     private String cnomalu;
     private String curso;
     private Set asignaturases = new HashSet(0);
     private Set expedienteses = new HashSet(0);

    public Alumnos() {
    }

	
    public Alumnos(String ccodalu, String cnomalu, String curso) {
        this.ccodalu = ccodalu;
        this.cnomalu = cnomalu;
        this.curso = curso;
    }
    public Alumnos(String ccodalu, String cnomalu, String curso, Set asignaturases, Set expedienteses) {
       this.ccodalu = ccodalu;
       this.cnomalu = cnomalu;
       this.curso = curso;
       this.asignaturases = asignaturases;
       this.expedienteses = expedienteses;
    }
   
    public String getCcodalu() {
        return this.ccodalu;
    }
    
    public void setCcodalu(String ccodalu) {
        this.ccodalu = ccodalu;
    }
    public String getCnomalu() {
        return this.cnomalu;
    }
    
    public void setCnomalu(String cnomalu) {
        this.cnomalu = cnomalu;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public Set getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set asignaturases) {
        this.asignaturases = asignaturases;
    }
    public Set getExpedienteses() {
        return this.expedienteses;
    }
    
    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }




}


