package modelo;
// Generated 02-dic-2018 21:50:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {


     private String ccodasig;
     private Profesores profesores;
     private String cnomasig;
     private Set alumnoses = new HashSet(0);
     private Set expedienteses = new HashSet(0);

    public Asignaturas() {
    }

	
    public Asignaturas(String ccodasig, Profesores profesores, String cnomasig) {
        this.ccodasig = ccodasig;
        this.profesores = profesores;
        this.cnomasig = cnomasig;
    }
    public Asignaturas(String ccodasig, Profesores profesores, String cnomasig, Set alumnoses, Set expedienteses) {
       this.ccodasig = ccodasig;
       this.profesores = profesores;
       this.cnomasig = cnomasig;
       this.alumnoses = alumnoses;
       this.expedienteses = expedienteses;
    }
   
    public String getCcodasig() {
        return this.ccodasig;
    }
    
    public void setCcodasig(String ccodasig) {
        this.ccodasig = ccodasig;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getCnomasig() {
        return this.cnomasig;
    }
    
    public void setCnomasig(String cnomasig) {
        this.cnomasig = cnomasig;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set getExpedienteses() {
        return this.expedienteses;
    }
    
    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }




}


