package modelo;
// Generated 02-dic-2018 21:50:03 by Hibernate Tools 4.3.1



/**
 * ExpedientesId generated by hbm2java
 */
public class ExpedientesId  implements java.io.Serializable {


     private String ccodalu;
     private String ccodasig;
     private String curso;
     private String evaluac;

    public ExpedientesId() {
    }

    public ExpedientesId(String ccodalu, String ccodasig, String curso, String evaluac) {
       this.ccodalu = ccodalu;
       this.ccodasig = ccodasig;
       this.curso = curso;
       this.evaluac = evaluac;
    }
   
    public String getCcodalu() {
        return this.ccodalu;
    }
    
    public void setCcodalu(String ccodalu) {
        this.ccodalu = ccodalu;
    }
    public String getCcodasig() {
        return this.ccodasig;
    }
    
    public void setCcodasig(String ccodasig) {
        this.ccodasig = ccodasig;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getEvaluac() {
        return this.evaluac;
    }
    
    public void setEvaluac(String evaluac) {
        this.evaluac = evaluac;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExpedientesId) ) return false;
		 ExpedientesId castOther = ( ExpedientesId ) other; 
         
		 return ( (this.getCcodalu()==castOther.getCcodalu()) || ( this.getCcodalu()!=null && castOther.getCcodalu()!=null && this.getCcodalu().equals(castOther.getCcodalu()) ) )
 && ( (this.getCcodasig()==castOther.getCcodasig()) || ( this.getCcodasig()!=null && castOther.getCcodasig()!=null && this.getCcodasig().equals(castOther.getCcodasig()) ) )
 && ( (this.getCurso()==castOther.getCurso()) || ( this.getCurso()!=null && castOther.getCurso()!=null && this.getCurso().equals(castOther.getCurso()) ) )
 && ( (this.getEvaluac()==castOther.getEvaluac()) || ( this.getEvaluac()!=null && castOther.getEvaluac()!=null && this.getEvaluac().equals(castOther.getEvaluac()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCcodalu() == null ? 0 : this.getCcodalu().hashCode() );
         result = 37 * result + ( getCcodasig() == null ? 0 : this.getCcodasig().hashCode() );
         result = 37 * result + ( getCurso() == null ? 0 : this.getCurso().hashCode() );
         result = 37 * result + ( getEvaluac() == null ? 0 : this.getEvaluac().hashCode() );
         return result;
   }   


}


