package modelo;
// Generated 02-dic-2018 21:50:03 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String ccodusu;
     private String cnomusu;
     private String tipo;
     private String psw;

    public Usuarios() {
    }

    public Usuarios(String ccodusu, String cnomusu, String tipo, String psw) {
       this.ccodusu = ccodusu;
       this.cnomusu = cnomusu;
       this.tipo = tipo;
       this.psw = psw;
    }
   
    public String getCcodusu() {
        return this.ccodusu;
    }
    
    public void setCcodusu(String ccodusu) {
        this.ccodusu = ccodusu;
    }
    public String getCnomusu() {
        return this.cnomusu;
    }
    
    public void setCnomusu(String cnomusu) {
        this.cnomusu = cnomusu;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getPsw() {
        return this.psw;
    }
    
    public void setPsw(String psw) {
        this.psw = psw;
    }




}


